### ISSUE TITLE
Lab-J code issue

### ISSUE THREAD

**Issue by lhardee-chase** [mafudge/ist346-labs#11]
Firewall not enabled after installation and anytime ufw command was used in lab.

![image](https://user-images.githubusercontent.com/43323846/122614461-b0626200-d054-11eb-8c21-f6fa298afb47.png)

![image](https://user-images.githubusercontent.com/43323846/122614498-c40dc880-d054-11eb-9f62-a93bcf448f7e.png)

**Comment by mafudge** [comment]
firewall must be enabled manually with 
`ufw enable`
and disabled with 
`ufw disable`

**Comment by mafudge** [comment]
lab updated
